[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && gunicorn blog_noticias.wsgi --log-file -"
restartPolicyType = "on_failure"
