# Generated by Django 5.2.3 on 2026-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categoria_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destacada',
            field=models.BooleanField(default=False, help_text='Mostrar esta noticia en primer lugar en el home', verbose_name='Destacada'),
        ),
    ]
