# Generated by Django 5.2.3 on 2026-04-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_destacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='meta_descripcion',
            field=models.CharField(blank=True, help_text='Resumen para motores de búsqueda y redes sociales (máx. 160 caracteres). Si se deja vacío se genera automáticamente.', max_length=160, verbose_name='Meta descripción'),
        ),
    ]
